services:
  flask:
    build: ./recommendation_algorithm
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./recommendation_algorithm/requirements.txt
        - action: sync
          path: ./recommendation_algorithm
          target: /recommendation_algorithm
    networks:
      - default
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    depends_on:
      - db
    environment:
      APP_NAME: ${APP_NAME}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    networks:
      - inside
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:${MYSQL_PORT}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DB}
  db:
    image: mysql:latest
    container_name: db
    networks:
      - inside
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    command: --init-file /mysql-init/init.sql
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/mysql-init
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - inside
    environment:
      PMA_HOST: db
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PMA_PORT}:80
volumes:
  db_data:
networks:
  inside:

